use std::fs;
use crate::isa::Op;

pub fn assemble(input: &str, output_file: &str) {

    // Read the assembly source file
    let contents = fs::read_to_string(input)
        .expect("Failed to read assembly file");

    // Store parsed instructions
    let mut program: Vec<Op> = Vec::new();

    // Read the file line by line
    for (line_number, line) in contents.lines().enumerate() {

        // Remove comments
        let line = line.split(';').next().unwrap().trim();

        // Ignore blank lines
        if line.is_empty() {
            continue;
        }

        // Split into tokens
        let parts: Vec<&str> = line.split_whitespace().collect();

        // Make instructions case-insensitive
        let instruction = parts[0].to_uppercase();

        match instruction.as_str() {

            "PUSH" => {
                if parts.len() != 2 {
                    println!("Error on line {}: PUSH requires one operand", line_number + 1);
                    return;
                }

                let value: i64 = parts[1]
                    .parse()
                    .expect("Invalid number");

                program.push(Op::Push(value));
            }

            "POP" => program.push(Op::Pop),

            "DUP" => program.push(Op::Dup),

            "SWAP" => program.push(Op::Swap),

            "ADD" => program.push(Op::Add),

            "SUB" => program.push(Op::Sub),

            "MUL" => program.push(Op::Mul),

            "DIV" => program.push(Op::Div),

            "MOD" => program.push(Op::Mod),

            "NEG" => program.push(Op::Neg),

            "LOAD" => {
                if parts.len() != 2 {
                    println!("Error on line {}: LOAD requires one operand", line_number + 1);
                    return;
                }

                let slot: u8 = parts[1]
                    .parse()
                    .expect("Invalid slot number");

                program.push(Op::Load(slot));
            }

            "STORE" => {
                if parts.len() != 2 {
                    println!("Error on line {}: STORE requires one operand", line_number + 1);
                    return;
                }

                let slot: u8 = parts[1]
                    .parse()
                    .expect("Invalid slot number");

                program.push(Op::Store(slot));
            }

            "PRINT" => program.push(Op::Print),

            "HALT" => program.push(Op::Halt),

            _ => {
                println!(
                    "Unknown instruction '{}' on line {}",
                    instruction,
                    line_number + 1
                );
                return;
            }
        }
    }

    // Display parsed instructions
    println!("\nParsed Instructions:\n");

    for instruction in &program {
        println!("{:?}", instruction);
    }

    // Encode into bytecode
    let bytecode = encode(&program);

    println!("\nGenerated Bytecode:");

    for byte in &bytecode {
        print!("{:02X} ", byte);
    }

    println!();

    // Create output file
    let mut output: Vec<u8> = Vec::new();

    // Magic Number: MVM\0
    output.extend_from_slice(b"MVM\0");

    // Version
    output.push(1);

    // Code Length (little-endian u32)
    let length = bytecode.len() as u32;
    output.extend_from_slice(&length.to_le_bytes());

    // Actual bytecode
    output.extend_from_slice(&bytecode);

    // Write output file
    fs::write(output_file, output)
        .expect("Unable to write output file");

    println!("\nAssembly successful!");
    println!("Output written to {}", output_file);
}

fn encode(program: &Vec<Op>) -> Vec<u8> {

    let mut bytes: Vec<u8> = Vec::new();

    for instruction in program {

        // Write opcode
        bytes.push(instruction.opcode());

        match instruction {

            // PUSH has an i64 operand
            Op::Push(value) => {
                bytes.extend_from_slice(&value.to_le_bytes());
            }

            // LOAD has a one-byte operand
            Op::Load(slot) => {
                bytes.push(*slot);
            }

            // STORE has a one-byte operand
            Op::Store(slot) => {
                bytes.push(*slot);
            }

            // Remaining instructions have no operands
            _ => {}
        }
    }

    bytes
}